pages/urls.py
app_name = "pages"

urlpatterns = [

]

parakeet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(route='admin/', view=admin.site.urls),
    path(
        route='pages/',
        view=include(
            arg='pages.urls',
            namespace='pages'
        )
    ),
    path(
        route='posts/',
        view=include(
            arg='posts.urls',
            namespace='posts'
        )
    ),
    path(
        route='profiles',
        view=include(
            arg='profiles.urls',
            namespace='profiles'
        )
    )
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path

from posts.views import *

app_name = "posts"

urlpatterns = [
    path(
        route='',
        view=post_list,
        name='post_list'
    ),
    path(
        route='create/',
        view=post_create,
        name='post_create'
    ),
    path(
        route='like/<int:post_id>/',
        view=post_like,
        name='post_like'
    )
]

profiles/urls.py
from django.urls import path

from profiles.views import *

app_name = 'profiles'

urlpatterns = []

pages/models.py
# Create your models here.

posts/models.py
from django.conf import settings
from django.db import models


class PostModelManager(models.Manager):
    def get_queryset(self):
        return (
            super().get_queryset().filter(status=Post.Status.PUBLISHED)
        )


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DFT', 'Draft'
        PUBLISHED = 'PBL', 'Published'

    content = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=3,
        choices=Status,
        default=Status.PUBLISHED
    )
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        related_name='posts',
        on_delete=models.CASCADE
    )

    objects = models.Manager()
    published = PostModelManager()

    def __str__(self):
        return self.content[:50]

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]


class Like(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        to=Post,
        on_delete=models.CASCADE,
        related_name='likes'
    )
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        related_name='likes',
        on_delete=models.CASCADE
    )

profiles/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import *

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'status']
        labels = {
            'content': '',
            'status': '',
        }
        widgets = {
            'content': Textarea(
                attrs={
                    'class': 'form__post-content',
                    'placeholder': 'What\'s chirping?',
                    'maxlength': 250,
                    'rows': 5,
                }
            ),
            'status': Select(
                attrs={
                    'class': 'form__post-status'
                }
            )
        }

pages/views.py
# Create your views here.

posts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse

from posts.forms import PostForm
from posts.models import Post, Like


def post_list(request):
    form = PostForm()
    posts = Post.published.all()

    return render(
        request=request,
        template_name='posts/list.html',
        context={
            'posts': posts,
            'form': form
        }
    )


def post_create(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

        return redirect(reverse('posts:post_list'))

    return render(
        request=request,
        template_name='posts/list.html',
        context={'form': form}
    )


def post_like(request, post_id):
    author = request.user
    post = Post.objects.get(id=post_id)
    like = Like.objects.filter(post=post, author=author)

    if like.exists():
        like.delete()
    else:
        like = Like.objects.create(post=post, author=author)
        like.save()

    return redirect(reverse('posts:post_list'))

profiles/views.py
from django.shortcuts import render

# Create your views here.

pages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock title %}
  </title>

  {# Lato Font #}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
    rel="stylesheet"
  >

  {# Styles #}
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  {# Box icons #}
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

</head>
<body>
<header>
  {% include 'navbar.html' %}
</header>

{% block body %}
{% endblock body %}

<script type="text/javascript" src="{% static 'js/index.js' %}">

</script>
</body>
</html>

pages/templates/feed.html
{% extends "base.html" %}

{% block title %}
  Chirps
{% endblock title %}

{% block body %}
  <main>
    <section class="profile">
      {% block profile %}
      {% endblock profile %}
    </section>
    <section class="feed">
      {% block feed %}
      {% endblock feed %}
    </section>
    <section class="trending">
      {% block trending %}
      {% endblock trending %}
    </section>
  </main>
{% endblock body %}

pages/templates/navbar.html
{% load static %}

<nav class="navbar">
  <ul class="navbar__main">
    <li class="navbar__item">
      <a class="navbar__link" href="">
        <i type="solid" class="bx bxs-home"></i>
        <span>Home</span>
      </a>
    </li>
    <li class="navbar__item">
      <a class="navbar__link" href="">
        <i type="solid" class="bx bxs-bell"></i>
        <span>Notifications</span>
      </a>
    </li>
    <li class="navbar__item">
      <a class="navbar__link" href="">
        <i class="bx bxs-chat"></i>
        <span>Messages</span>
      </a>
    </li>
  </ul>
  <div class="navbar__options">
    <form class="form form--search">
      <label for="form__search-input"></label>
      <input
        id="form__search-input"
        class="form__search-input"
        type="text"
        placeholder="Search Parakeet"
      >
    </form>
    <figure class="navbar__avatar">
      <a href="#" class="navbar__avatar__link">
        <img
          class="navbar__avatar__img"
          src="{% static 'img/kid.jpg' %}"
          alt="Profile picture"
        >
      </a>
    </figure>
    <button class="navbar__chirp">
      <i class="bx bxs-pencil"></i>
      <span>Chirp</span>
    </button>
  </div>
</nav>

pages/templates/pages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
    {% endblock title %}
  </title>
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>

posts/templates/posts/components/chirp.html
{% load post_tags %}
{% load static %}

<article
  class="post"
  data-liked="{% if post|post_liked:user %}true{% else %}false{% endif %}"
>
  <section class="post__avatar">
    <img class="post__avatar__img" src="{% static 'img/kid.jpg' %}" alt="Profile picture">
  </section>
  <section class="post__body">
    <section class="post__handle">
      <h2 class="post__name">
        {% if post.author.first_name and post.author.last_name %}
          {{ post.author.first_name }} {{ post.author.last_name }}
        {% else %}
          {{ post.author.username }}
        {% endif %}
      </h2>
      <h3 class="post__username">
        @{{ post.author.username }}
      </h3>
    </section>
    <p class="post__content">{{ post.content }}</p>
    {% include "posts/components/chirp_actions.html" with post=post %}
  </section>
</article>

posts/templates/posts/components/chirp_actions.html
<section class="post__engagements">
  <form
    action="{% url 'posts:post_like' post.pk %}"
    class="post__engagement post__engagement--like"
    method="post"
  >
    {% csrf_token %}
    <button>
      <i class='bx bx-star'></i>
    </button>
    <label class="like__counter">{{ post.likes.count }}</label>
  </form>
  <div class="post__engagement post__engagement--reply">
    <button>
      <i class='bx bx-message-alt-dots'></i>
    </button>
    <label>0</label>
  </div>
  <div class="post__engagement post__engagement--share">
    <button>
      <i class='bx bx-share'></i>
    </button>
  </div>
  <p class="post__show">
    <a class="link" href="#">
      Show this thread
    </a>
  </p>
</section>

posts/templates/posts/list.html
{% extends "feed.html" %}

{% load static %}

{% block feed %}
  {# Add chirps form #}
  <form class="form form--post" action="{% url 'posts:post_create' %}" method="post">
    {% csrf_token %}
    {{ form.content.as_field_group }}
    <div class="form__post-actions">
      <p class="form__post-counter">0</p>
      {{ form.status.as_field_group }}
      <input class="form__post-submit" type="submit" value="Post">
    </div>
  </form>

  {# List of chirps #}
  <div class="posts">
    {% for post in posts %}
      {% include "posts/components/chirp.html" with post=post %}
    {% endfor %}
  </div>
{% endblock feed %}